schemaVersion: "1.0"
pattern:
  id: "fd5af616a9d8c7579a2f0aa8"
  className: "ch.nevis.admin.v4.plugin.nevismeta.patterns.CustomNevisMetaLogFile"
  name: "nevisMeta log settings"
  properties:
    logLevel: "INFO"
