schemaVersion: "1.0"
pattern:
  id: "826897d4f7dcf0bcf5df1637"
  className: "ch.nevis.admin.v4.plugin.nevisfido.deployable.patterns.NevisFIDOLogSettings"
  name: "nevisFIDO log settings"
  properties:
    logLevel: "INFO"
