schemaVersion: "1.0"
pattern:
  id: "c27e0cd5ab6b34babac672af"
  className: "ch.nevis.admin.v4.plugin.nevisproxy.patterns.CustomProxyLogFile"
  name: "nevisProxy log settings"
  properties:
    logLevel: "INFO"
